---
title: "About Body Image"
author: "Cierra Bustamantes"
output:
    html_document:
      theme: cosmo
---
What is Body Image?
Body image relates to a person’s perceptions, feelings and thoughts about his or her body, and is usually conceptualized as incorporating body size estimation,evaluation of body attractiveness and emotions associated with body shape and size.

Body image is a persons thoughts and feelings about their own body which then leads to how attractive they feel based on their size and shape.

How early can body image come into the picture?
Nearly 2/3 (64 %) of parents say their child is self-conscious about some aspect of their appearance.

1 in 5 parents say their teens avoid things like being in photos due to being self-conscious about their appearance.

Research has shown that around 50% of young 13 year old girls reported being unhappy with their body. This number grew to nearly 80% by the time girls reached 17 years of age


In U.S adult women, 23% reported frequent body checking and 11% reported body image avoidance


One study found using social media for as little as 30 minutes a day can negatively change the way young women view their own body